plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'cn.huohuas001'
version = '1.0.1'

repositories {
    mavenCentral()
    maven {
        name = "spigotmc-repo"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name = "placeholder"
        url = 'https://repo.extendedclip.com/releases/'
    }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'com.h2database:h2:1.4.200'
    compileOnly "org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT"
    implementation 'org.jetbrains:annotations:24.0.1'
    implementation 'com.github.Anon8281:UniversalScheduler:0.1.6'
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
}


jar {
    archiveFileName = 'HuHoWhiteList.jar'
    manifest {
        attributes 'Main-Class': 'cn.huohuas001.huhomonitor'
    }
}

// 删除原有的 jar 配置块
shadowJar {
    archiveFileName = "HuHoWhiteList-${project.version}-Spigot.jar"
    manifest {
        attributes 'Main-Class': 'cn.huohuas001.huhowhitelist'
    }
    relocate 'org.h2', 'cn.huohuas001.shaded.h2'
    relocate 'com.github.Anon8281.universalScheduler', 'cn.huohuas001.huhowhitelist.universalScheduler'
    //minimize() // 自动移除未使用的类
    exclude 'META-INF/maven/**' // 排除冗余文件
    exclude '**/*.properties' // 排除非必要配置文件

    // 显式包含 HuHoBot 的依赖
    //from(project.configurations.compileClasspath)
}

def targetJavaVersion = 8
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
    filesMatching('config.yml') {
        expand props
    }
}
